apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vt1u17x59-go
  janus-idp.io/tekton: vt1u17x59-go
  backstage.io/kubernetes-id: vt1u17x59-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vt1u17x59-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
